// update-gha-workflows.ts — Regenerate CI files that reference individual workspaces.
//
// Fully regenerated:
//   .github/path-filters.yml    — per-workspace path filters (global paths + transitive deps)
//
// Incrementally updated (new entries added, existing ones preserved):
//   .github/workflows/publish.yml — per-workspace npm publish steps
//
// Usage:
//   npx ts-node scripts/update-gha-workflows.ts
//   npm run refresh-gh-workflow

import {exec} from 'child_process';
import fs from 'fs';
import path from 'path';
import {promisify} from 'util';

const execAsync = promisify(exec);

// ─── Types ───────────────────────────────────────────────────────────────────

type PackageJson = {
    name: string;
    location: string;
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    peerDependencies?: Record<string, string>;
};

type Workspace = {
    /** Full npm name, e.g. "@scratch/scratch-vm" */
    name: string;
    /** Bare name, e.g. "scratch-vm" */
    bareName: string;
    /** Relative dir, e.g. "packages/scratch-vm" */
    location: string;
    /** Direct workspace dependencies (production only) */
    directDeps: string[];
    /** Transitive closure of workspace dependencies (production only), including self */
    deepDeps: string[];
};

// ─── Dependency resolution ───────────────────────────────────────────────────

function resolveWorkspaces(packages: PackageJson[]): Workspace[] {
    const nameSet = new Set(packages.map(p => p.name));

    // Build workspace records with direct deps
    const workspaceMap = new Map<string, Workspace>();
    for (const pkg of packages) {
        const bareName = path.basename(pkg.location);
        const directDeps = Object.keys(pkg.dependencies ?? {}).filter(d => nameSet.has(d));
        workspaceMap.set(pkg.name, {
            name: pkg.name,
            bareName,
            location: pkg.location,
            directDeps,
            deepDeps: [],
        });
    }

    // Compute transitive closure (production deps only)
    function collectDeep(name: string, visited: Set<string>): void {
        if (visited.has(name)) return;
        visited.add(name);
        const ws = workspaceMap.get(name);
        if (!ws) return;
        for (const dep of ws.directDeps) {
            collectDeep(dep, visited);
        }
    }

    for (const ws of workspaceMap.values()) {
        const visited = new Set<string>();
        collectDeep(ws.name, visited);
        ws.deepDeps = [...visited];
    }

    // Returned in Map insertion order, which matches the order of the input
    // `packages` array (i.e. the order `npm query .workspace` produced).
    // Re-sorting into the declared workspaces order is done by the caller.
    return [...workspaceMap.values()];
}

// ─── path-filters.yml generation ─────────────────────────────────────────────

const PATH_FILTERS_HEADER = `\
# This file is generated by scripts/update-gha-workflows.ts
#
# To regenerate:  npm run refresh-gh-workflow
`;

const GLOBAL_PATHS = [
    '.github/path-filters.yml',
    '.github/workflows/ci.yml',
    '.nvmrc',
    'package.json',
    'package-lock.json',
    'scripts/**',
];

function generatePathFilters(workspaces: Workspace[], workspaceMap: Map<string, Workspace>): string {
    const lines: string[] = [];

    // Header comment
    lines.push(PATH_FILTERS_HEADER);

    // global anchor
    lines.push('# The `&global` anchor defines a set of common paths to include by reference in the other filters.');
    lines.push('global: &global');
    for (const p of GLOBAL_PATHS) {
        lines.push(`  - "${p}"`);
    }
    lines.push('');

    // any-workspace
    lines.push('any-workspace:');
    lines.push('  - *global');
    lines.push('  - "packages/**"');
    lines.push('');

    // Per-workspace entries, each including self + all transitive production deps
    for (const ws of workspaces) {
        lines.push(`${ws.bareName}:`);
        lines.push('  - *global');

        // Collect all package directories (self + transitive deps), sorted for stability
        const depLocations = ws.deepDeps
            .map(depName => workspaceMap.get(depName)!)
            .map(dep => dep.location)
            .sort();

        for (const loc of depLocations) {
            lines.push(`  - "${loc}/**"`);
        }
    }

    lines.push('');
    return lines.join('\n');
}

// ─── publish.yml update ──────────────────────────────────────────────────────

const PUBLISH_STEP_MARKER =
    '# update-gha-workflows.ts: insert new "Publish <package>" steps before this line.';

/**
 * Scans publish.yml for existing "Publish <name>" steps and adds a default
 * publish step for any workspace that doesn't already have one.
 *
 * Packages that should NOT be auto-published (virtual packages, meta-packages,
 * packages with special publish logic already present) are skipped if they
 * already have a step — they are never removed.
 */
// TODO: Add exclude list for packages that we don't want to auto-publish,
// as they are introduced to the monorepo.
function updatePublishWorkflow(content: string, workspaces: Workspace[]): string {
    // Find all existing "- name: Publish <something>" step names
    const existingPublishSteps = new Set<string>();
    const publishStepRegex = /- name: Publish (.+)$/gm;
    let match: RegExpExecArray | null;
    while ((match = publishStepRegex.exec(content)) !== null) {
        existingPublishSteps.add(match[1].trim());
    }

    // Determine which workspaces need a new publish step
    const missing: Workspace[] = [];
    for (const ws of workspaces) {
        // Check if there's already a publish step matching this workspace's bare name
        if (existingPublishSteps.has(ws.bareName)) continue;
        // Also check for any step that mentions the full @scratch/ name in its title
        if (existingPublishSteps.has(ws.name)) continue;
        missing.push(ws);
    }

    if (missing.length === 0) {
        return content;
    }

    // Build the new publish steps
    const newSteps = missing.map(ws => {
        return [
            `      - name: Publish ${ws.bareName}`,
            `        run: npm publish --access=public --tag="$NPM_TAG" --ignore-scripts --workspace=${ws.name}`,
        ].join('\n');
    }).join('\n\n');

    // A missing marker is fatal rather than a warning: silently dropping
    // publish steps would let workflow drift go unnoticed. The match is
    // indent-tolerant so the YAML formatter is free to pick a column.
    const markerRegex = new RegExp(
        `^[ \\t]*${PUBLISH_STEP_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[ \\t]*$`,
        'm',
    );
    const markerMatch = markerRegex.exec(content);
    if (!markerMatch) {
        const wanted = missing.map(ws => `  - Publish ${ws.bareName}`).join('\n');
        throw new Error(
            `Could not find the insert marker in publish.yml. ` +
            `Expected to find a line containing:\n  ${PUBLISH_STEP_MARKER}\n` +
            `Add it back (at the bottom of the cd: job's steps, before the next job) ` +
            `or update PUBLISH_STEP_MARKER in scripts/update-gha-workflows.ts.\n` +
            `New publish steps that were NOT added:\n${wanted}`,
        );
    }

    const insertIndex = markerMatch.index;
    return content.slice(0, insertIndex) + newSteps + '\n\n' + content.slice(insertIndex);
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
    const repoRoot = path.resolve(__dirname, '..');
    const ghDir = path.join(repoRoot, '.github');
    const workflowsDir = path.join(ghDir, 'workflows');

    // 1. Query workspaces
    // The default exec maxBuffer of 1 MiB can be exceeded as the monorepo
    // grows; bump it to 64 MiB so this scales without surprise.
    console.log('Querying workspaces...');
    const {stdout} = await execAsync('npm query .workspace', {maxBuffer: 64 * 1024 * 1024});
    const packages = JSON.parse(stdout) as PackageJson[];
    console.log(`  Found ${packages.length} workspaces`);

    // 2. Resolve dependencies
    console.log('Resolving transitive dependencies...');
    const resolvedWorkspaces = resolveWorkspaces(packages);
    const workspaceMap = new Map(resolvedWorkspaces.map(ws => [ws.name, ws]));

    // Sort by the declared order in the root package.json workspaces array
    // (npm query .workspace returns packages alphabetically, not in declaration order)
    const rootPackageJson = JSON.parse(fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8'));
    const declaredOrder: string[] = (rootPackageJson.workspaces as string[]).map(
        (ws: string) => path.basename(ws),
    );

    // Validate that every resolved workspace appears in the declared workspaces
    // array. If one is missing, indexOf would return -1 and silently misorder
    // entries (corrupting path-filters.yml and publish.yml output downstream).
    const missing = resolvedWorkspaces
        .map(ws => ws.bareName)
        .filter(name => !declaredOrder.includes(name));
    if (missing.length > 0) {
        throw new Error(
            `npm query .workspace returned ${missing.length} workspace(s) not present in ` +
            `the root package.json "workspaces" array: ${missing.join(', ')}. ` +
            `Update root package.json or investigate why npm sees orphan workspaces.`,
        );
    }

    const workspaces = resolvedWorkspaces.sort(
        (a, b) => declaredOrder.indexOf(a.bareName) - declaredOrder.indexOf(b.bareName),
    );

    for (const ws of workspaces) {
        const depNames = ws.deepDeps.filter(d => d !== ws.name).map(d => workspaceMap.get(d)!.bareName);
        if (depNames.length > 0) {
            console.log(`  ${ws.bareName} → ${depNames.join(', ')}`);
        } else {
            console.log(`  ${ws.bareName} (no workspace deps)`);
        }
    }

    // 3. Regenerate path-filters.yml
    console.log('Generating .github/path-filters.yml...');
    const pathFiltersPath = path.join(ghDir, 'path-filters.yml');
    const pathFiltersContent = generatePathFilters(workspaces, workspaceMap);
    fs.mkdirSync(ghDir, {recursive: true});
    fs.writeFileSync(pathFiltersPath, pathFiltersContent, 'utf8');
    console.log(`  Wrote ${pathFiltersPath}`);

    // 4. Update publish.yml
    const publishPath = path.join(workflowsDir, 'publish.yml');
    if (fs.existsSync(publishPath)) {
        console.log('Updating .github/workflows/publish.yml...');
        const originalPublish = fs.readFileSync(publishPath, 'utf8');
        const updatedPublish = updatePublishWorkflow(originalPublish, workspaces);
        if (updatedPublish !== originalPublish) {
            fs.writeFileSync(publishPath, updatedPublish, 'utf8');
            console.log('  Added new publish steps.');
        } else {
            console.log('  No changes needed.');
        }
    } else {
        console.warn('Warning: .github/workflows/publish.yml not found. Skipping publish step generation.');
    }

    console.log('Done.');
}

main().then(
    () => {
        process.exitCode = 0;
    },
    e => {
        console.error(e);
        process.exitCode = 1;
    },
);
